name: Run Python Script

on:
  push:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch
        run: |
          # Configure git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Create release branch with date
          RELEASE_BRANCH="release-$(date +'%Y-%m-%d')"

          echo "Creating release branch: $RELEASE_BRANCH"

          # Check if branch already exists
          if git ls-remote --exit-code --heads origin $RELEASE_BRANCH; then
            echo "Release branch already exists. Skipping creation."
          else
            git checkout -b $RELEASE_BRANCH
            git push origin $RELEASE_BRANCH
            echo "Release branch pushed successfully."
          fi

    
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Execute Python script
        run: python hello.py
